### ISSUE TITLE
Support SCRAM-SHA-256

### ISSUE THREAD

**Issue by thekid** [xp-forge/mongodb#8]
The README [states](https://github.com/xp-forge/mongodb#ssl--tls):

> Currently, SCRAM-SHA-1 is the only supported authentication mechanism.

However, https://docs.mongodb.com/manual/core/security-scram/ also lists SCRAM-SHA-256

**Comment by thekid** [comment]
https://github.com/mongodb/mongo-go-driver/blob/master/x/mongo/driver/auth/scram.go might be a good starting point.

**Comment by thekid** [comment]
Currently, Atlas does not support SCRAM-SHA-256, see https://www.mongodb.com/community/forums/t/badvalue-scram-sha-256-authentication-is-disabled/143254/2

**Comment by Neustradamus** [comment]
Hello @thekid, have you looked for SCRAM-SHA-256 support?
- https://www.mongodb.com/docs/manual/core/security-scram/

**Comment by thekid** [comment]
It's low on my priorities because I personally use MongoDB Atlas, which doesn't support it, so I'm happy with SHA1 ☺️

**Comment by thekid** [comment]
It was actually quite easy: SCRAM-SHA-256 is the same as SCRAM-SHA-1 but doesn't use digests for passwords.

**Comment by thekid** [comment]
Released in https://github.com/xp-forge/mongodb/releases/tag/v1.14.0

**Comment by Neustradamus** [comment]
@thekid: Thanks a lot!

Linked to:
- https://github.com/scram-sasl/info/issues/1

**Comment by Neustradamus** [comment]
@thekid: Can you add the scram-sha-256 topic at this repository? ^^

**Comment by thekid** [comment]
> @thekid: Can you add the scram-sha-256 topic at this repository? ^^

Sure! Updated `README` - see [here](https://github.com/xp-forge/mongodb#authentication) - and added the [scram-sha-256](https://github.com/topics/scram-sha-256) topic.
